UrunYonetimStokTakip.WebUI/Areas/Admin/Controllers/UrunsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UrunYonetimStokTakip.WebUI.Models;
using UrunYonetimi.Entites;
using BuisnessLayer;
using UrunYonetim.BuisnessLayer;
using System.IO;

namespace UrunYonetimStokTakip.WebUI.Areas.Admin.Controllers
{
    public class UrunsController : Controller
    {
        private ModelDb db = new ModelDb();
        UrunManager Umanager = new UrunManager();
        MarkaManager Mmanager = new MarkaManager();
        KategoriManager Kmanager = new KategoriManager();
        // GET: Admin/Uruns
        public ActionResult Index()
        {
            //var urunler = db.Urunler.Include(u => u.Kategori).Include(u => u.Marka);
            var urunler = Umanager.GetAll();
            return View(urunler);
        }

        // GET: Admin/Uruns/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Urun urun = Umanager.Find(i => i.id == id.Value);
            if (urun == null)
            {
                return HttpNotFound();
            }
            return View(urun);
        }

        // GET: Admin/Uruns/Create
        public ActionResult Create()
        {
            ViewBag.KategoriId = new SelectList(Kmanager.GetAll(), "id", "KategoriAdi");
            ViewBag.MarkaId = new SelectList(Mmanager.GetAll(), "id", "MarkaAdi");
            return View();
        }

        // POST: Admin/Uruns/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Urun urun , HttpPostedFileBase ResimUrl)
        {
            if (ModelState.IsValid)
            {
                if (ResimUrl != null)
                {
                    //string directory = Server.MapPath("~/Img/");
                    //var fileName = Path.GetFileName(ResimUrl.FileName);
                    //ResimUrl.SaveAs(Path.Combine());
                    //urun.ResimUrl = ResimUrl.FileName;
                }
                //db.Urunler.Add(urun);
                //db.SaveChanges();
                urun.AktifMi = true;
                urun.EklenmeTarihi = Convert.ToDateTime(DateTime.Now.ToShortDateString());
                Umanager.Add(urun);
                return RedirectToAction("Index");
            }

            ViewBag.KategoriId = new SelectList(Kmanager.GetAll(), "id", "KategoriAdi", urun.KategoriId);
            ViewBag.MarkaId = new SelectList(Mmanager.GetAll(), "id", "MarkaAdi", urun.MarkaId);
            return View(urun);
        }

        // GET: Admin/Uruns/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Urun urun = Umanager.Find(i => i.id == id.Value);
            if (urun == null)
            {
                return HttpNotFound();
            }
            ViewBag.KategoriId = new SelectList(Kmanager.GetAll(), "id", "KategoriAdi", urun.KategoriId);
            ViewBag.MarkaId = new SelectList(Mmanager.GetAll(), "id", "MarkaAdi", urun.MarkaId);
            return View(urun);
        }

        // POST: Admin/Uruns/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,KategoriId,MarkaId,UrunAdi,Aciklama,EklenmeTarihi,AktifMi,UrunFiyati,Kdv,StokMiktari,ToptanFiyat")] Urun urun)
        {
            if (ModelState.IsValid)
            {
                //db.Entry(urun).State = EntityState.Modified;
                //db.SaveChanges();
                Umanager.Update(urun);
                return RedirectToAction("Index");
            }
            ViewBag.KategoriId = new SelectList(Kmanager.GetAll(), "id", "KategoriAdi", urun.KategoriId);
            ViewBag.MarkaId = new SelectList(Mmanager.GetAll(), "id", "MarkaAdi", urun.MarkaId);
            return View(urun);
        }

        // GET: Admin/Uruns/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Urun urun = Umanager.Find(i => i.id == id.Value);
            if (urun == null)
            {
                return HttpNotFound();
            }
            return View(urun);
        }

        // POST: Admin/Uruns/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Urun urun = Umanager.Find(i => i.id == id);
            Umanager.Delete(id);

            return RedirectToAction("Index");
        }


    }
}

UrunYonetimStokTakip.WebUI/Areas/Admin/Views/Uruns/Create.cshtml
@model UrunYonetimi.Entites.Urun

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create","Uruns" , FormMethod.Post , new {enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.KategoriId, "KategoriId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("KategoriId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.KategoriId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MarkaId, "MarkaId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MarkaId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MarkaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UrunAdi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UrunAdi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UrunAdi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Aciklama, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Aciklama, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Aciklama, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EklenmeTarihi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EklenmeTarihi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EklenmeTarihi, "", new { @class = "text-danger" })
            </div>
        </div>

        

        <div class="form-group">
            @Html.LabelFor(model => model.UrunFiyati, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UrunFiyati, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UrunFiyati, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Kdv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Kdv, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Kdv, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StokMiktari, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StokMiktari, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StokMiktari, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ToptanFiyat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ToptanFiyat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ToptanFiyat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ResimUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ResimUrl, new { htmlAttributes = new { @class = "form-control" , type="file"  } })
                @Html.ValidationMessageFor(model => model.ResimUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

UrunYonetimStokTakip.WebUI/Areas/Admin/Views/Uruns/Delete.cshtml
@model UrunYonetimi.Entites.Urun

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Urun</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Kategori.KategoriAdi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kategori.KategoriAdi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Marka.MarkaAdi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Marka.MarkaAdi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UrunAdi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UrunAdi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Aciklama)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Aciklama)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EklenmeTarihi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EklenmeTarihi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AktifMi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AktifMi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UrunFiyati)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UrunFiyati)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Kdv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kdv)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StokMiktari)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StokMiktari)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ToptanFiyat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ToptanFiyat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ResimUrl)
        </dt>

        <dd>

            @Html.DisplayFor(model => model.ResimUrl)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

UrunYonetimStokTakip.WebUI/Areas/Admin/Views/Uruns/Details.cshtml
@model UrunYonetimi.Entites.Urun

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Urun</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Kategori.KategoriAdi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kategori.KategoriAdi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Marka.MarkaAdi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Marka.MarkaAdi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UrunAdi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UrunAdi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Aciklama)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Aciklama)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EklenmeTarihi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EklenmeTarihi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AktifMi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AktifMi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UrunFiyati)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UrunFiyati)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Kdv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kdv)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StokMiktari)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StokMiktari)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ToptanFiyat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ToptanFiyat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ResimUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ResimUrl)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

UrunYonetimStokTakip.WebUI/Areas/Admin/Views/Uruns/Edit.cshtml
@model UrunYonetimi.Entites.Urun

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Urun</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.KategoriId, "KategoriId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("KategoriId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.KategoriId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MarkaId, "MarkaId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MarkaId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MarkaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UrunAdi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UrunAdi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UrunAdi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Aciklama, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Aciklama, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Aciklama, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EklenmeTarihi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EklenmeTarihi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EklenmeTarihi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AktifMi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.AktifMi)
                    @Html.ValidationMessageFor(model => model.AktifMi, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UrunFiyati, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UrunFiyati, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UrunFiyati, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Kdv, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Kdv, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Kdv, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StokMiktari, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StokMiktari, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StokMiktari, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ToptanFiyat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ToptanFiyat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ToptanFiyat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ResimUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ResimUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ResimUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

UrunYonetimStokTakip.WebUI/Areas/Admin/Views/Uruns/Index.cshtml
@model IEnumerable<UrunYonetimi.Entites.Urun>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Kategori.KategoriAdi)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Marka.MarkaAdi)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UrunAdi)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Aciklama)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EklenmeTarihi)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AktifMi)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UrunFiyati)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Kdv)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StokMiktari)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ToptanFiyat)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ResimUrl)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Kategori.KategoriAdi)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Marka.MarkaAdi)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UrunAdi)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Aciklama)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EklenmeTarihi)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AktifMi)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UrunFiyati)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Kdv)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StokMiktari)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ToptanFiyat)
        </td>
        <td>
            <img src="~/Img/@Html.DisplayFor(modelItem => item.ResimUrl)" height="40" alt="" />
            @*@Html.DisplayFor(modelItem => item.ResimUrl)*@
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>